export const REGISTRY_CONTRACT_REGISTRY_METADATA_RETURN_VALUE_SCHEMA =
    'FAADAAAADwAAAGlzc3Vlcl9tZXRhZGF0YRQAAgAAAAMAAAB1cmwWAQQAAABoYXNoFQIAAAAEAAAATm9uZQIEAAAAU29tZQEBAAAAHiAAAAAPAAAAY3JlZGVudGlhbF90eXBlFAABAAAADwAAAGNyZWRlbnRpYWxfdHlwZRYAEQAAAGNyZWRlbnRpYWxfc2NoZW1hFAABAAAACgAAAHNjaGVtYV9yZWYUAAIAAAADAAAAdXJsFgEEAAAAaGFzaBUCAAAABAAAAE5vbmUCBAAAAFNvbWUBAQAAAB4gAAAA';

export const GRPC_WEB_CONFIG = { baseUrl: 'https://grpc.testnet.concordium.com:20000' };

export const CONCORDIUM_TESTNET_BACKEND_API = 'https://web3id-verifier.testnet.concordium.com';

// Load an `env.js` file at runtime if it exists.
// The `env.js` file is generated by Nginx / Docker to inject environment variables at runtime.
const s = document.createElement('script');
s.src = '/env.js';
s.onload = () => {
    console.info('`env.js` file loaded. Using runtime environment variables from this file.');
};
s.onerror = () => {
    console.info(
        '`env.js` file not found. ' +
            'This file is generated by Nginx / Docker for runtime env injection when running the project from a docker image. ' +
            'Fallback to build-time environmental variables or default values instead.'
    );
};
document.head.appendChild(s);
