import { Network } from "@concordium/web-sdk";

export const REGISTRY_CONTRACT_REGISTRY_METADATA_RETURN_VALUE_SCHEMA =
    'FAADAAAADwAAAGlzc3Vlcl9tZXRhZGF0YRQAAgAAAAMAAAB1cmwWAQQAAABoYXNoFQIAAAAEAAAATm9uZQIEAAAAU29tZQEBAAAAHiAAAAAPAAAAY3JlZGVudGlhbF90eXBlFAABAAAADwAAAGNyZWRlbnRpYWxfdHlwZRYAEQAAAGNyZWRlbnRpYWxfc2NoZW1hFAABAAAACgAAAHNjaGVtYV9yZWYUAAIAAAADAAAAdXJsFgEEAAAAaGFzaBUCAAAABAAAAE5vbmUCBAAAAFNvbWUBAQAAAB4gAAAA';

export const GRPC_WEB_CONFIG = { baseUrl: 'https://grpc.testnet.concordium.com:20000' };

export const CONCORDIUM_TESTNET_BACKEND_API = 'https://web3id-verifier.testnet.concordium.com';
export const CONCORDIUM_TESTNET_V1_VERIFIER = 'https://credential-verification-service.testnet.concordium.com';

export const WALLET_CONNECT_PROJECT_ID = '76324905a70fe5c388bab46d3e0564dc';
export const WALLET_CONNECT_SESSION_NAMESPACE = 'concordium'; // concordium (ID App and new Android/iOS wallets)
export const CHAIN_ID = `ccd:4221332d34e1694168c2a0c0b3fd0f27`; // ccd:4221332d34e1694168c2a0c0b3fd0f27 (testnet: ID App and new Android/iOS wallets) // ccd:9dd9ca4d19e9393877d2c44b70f89acb (mainnet: ID App and new Android/iOS wallets)

// Old namespace/chainId used by `Android/iOS wallets`
export const WALLET_CONNECT_SESSION_NAMESPACE_OLD = 'ccd'; // ccd (old Android/iOS wallets)
export const CHAIN_ID_OLD = `ccd:testnet`; // ccd:testnet (old Android/iOS wallets)

export const NETWORK: Network = `Testnet`

export const REQUEST_VERIFIABLE_PRESENTATION_METHOD = 'request_verifiable_presentation';
export const REQUEST_VERIFIABLE_PRESENTATION_V1_METHOD = 'request_verifiable_presentation_v1';

// Load an `env.js` file at runtime if it exists.
// The `env.js` file is generated by Nginx / Docker to inject environment variables at runtime.
const s = document.createElement('script');
s.src = '/env.js';
s.onload = () => {
    console.info('`env.js` file loaded. Using runtime environment variables from this file.');
};
s.onerror = () => {
    console.info(
        '`env.js` file not found. ' +
        'This file is generated by Nginx / Docker for runtime env injection when running the project from a docker image. ' +
        'Fallback to build-time environmental variables or default values instead.'
    );
};
document.head.appendChild(s);
