CREATE TABLE IF NOT EXISTS verifications (
	id SERIAL8 PRIMARY KEY,
	presentation JSONB NOT NULL, -- presentation from generated by concordium wallet, which can be used to check the verification
	first_name VARCHAR NULL, -- from concordium identity
	last_name VARCHAR NULL, -- from concordium identity
	CONSTRAINT verifications_first_name_iff_last_name CHECK ((((first_name IS NULL) AND (last_name IS NULL)) OR ((first_name IS NOT NULL) AND (last_name IS NOT NULL))))
);

CREATE TABLE IF NOT EXISTS discord (
	id VARCHAR PRIMARY KEY, -- discord user ID
	cred_id BYTEA UNIQUE NOT NULL, -- ID of credential on chain.
	verification_id INT8 UNIQUE REFERENCES verifications(id) ON DELETE CASCADE,
	username VARCHAR NOT NULL -- discord username
);

CREATE TABLE IF NOT EXISTS telegram (
	id VARCHAR PRIMARY KEY, -- telegram user ID
	cred_id BYTEA UNIQUE NOT NULL, -- ID of credential on chain.
	verification_id INT8 UNIQUE REFERENCES verifications(id) ON DELETE CASCADE,
	username VARCHAR NOT NULL -- telegram username
);
